### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by danielkucera** [oskar456/happy-kaktus#1]
Ahoj,

vyborna vec! Slo by to prosim rozsirit aj o twitter?

```
import tweepy

# Authenticate to Twitter
auth = tweepy.OAuthHandler("CONSUMER_KEY", "CONSUMER_SECRET")
auth.set_access_token("ACCESS_TOKEN", "ACCESS_TOKEN_SECRET")

# Create API object
api = tweepy.API(auth)

# Create a tweet
api.update_status("Hello Tweepy")
```

**Comment by oskar456** [comment]
Dobrý nápad! Vyžadovalo by to trochu složitější logiku, protože poslání na dvě různé platformy může v různých okamžicích selhat.

Zatim jsem zřídil [účet](https://twitter.com/kvetinac_news) a nastavil přeposílání z telegramu pomocí IFTTT. Jenže Twitter účet zablokoval a požaduje ověření telefonního čísla, které selhává „kvůli technickým problémům.“ Snad se mi povede to zprovoznit.

**Comment by oskar456** [comment]
Tak IFTTT zdá se funguje, takže zatím takto. Někdy to třeba předělám na přímé postování, ale zatím to myslím takhle stačí.

**Comment by danielkucera** [comment]
Skvele! Dakujem velmi pekne.
